version: 2
jobs:
  build:
    docker:
      - image: docker:17.09

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t=geneerik/boinc-apk-builder $(pwd)
      - run: mkdir $(pwd)/artifacts
      - run: docker run -i -t -a stderr -a stdout -v $(pwd)/artifacts:/opt geneerik/boinc-apk-builder bash -i -c 'buildboincapkall.sh'
      - store_artifacts:
           path: ~/repo/artifacts

