version: 2
jobs:
  build:
    docker:
      - image:python:3.6

    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "Hello World"
      - run: touch $CIRCLE_ARTIFACTS/foobar.txt