version: 2
jobs:
  build:
    docker:
      - image: python:3.6

    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "Hello World"
      - run: echo "I am a text file" >  ~/repo/foobar.txt
      - store_artifacts:
           path: ~/repo/foobar.txt
           destination: foobar.txt

